import React from "react";

import MailIcon from '@mui/icons-material/Mail';
import PhoneIcon from '@mui/icons-material/Phone';
import PlaceIcon from '@mui/icons-material/Place';
import FacebookIcon from '@mui/icons-material/Facebook';
import InstagramIcon from '@mui/icons-material/Instagram';
import YouTubeIcon from '@mui/icons-material/YouTube';
import FavoriteIcon from '@mui/icons-material/Favorite';
import GroupIcon from '@mui/icons-material/Group';
import MenuBookIcon from '@mui/icons-material/MenuBook';
import PublicIcon from '@mui/icons-material/Public';
import ChildFriendlyIcon from '@mui/icons-material/ChildFriendly';
import SchoolIcon from '@mui/icons-material/School';
import HandshakeIcon from '@mui/icons-material/Handshake';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import EventIcon from '@mui/icons-material/Event';
import MenuIcon from '@mui/icons-material/Menu';
import CloseIcon from '@mui/icons-material/Close';
import MuiSearchIcon from '@mui/icons-material/Search';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import MoreHorizIcon from '@mui/icons-material/MoreHoriz';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import MuiCheckIcon from '@mui/icons-material/Check';
import RemoveIcon from '@mui/icons-material/Remove';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import RadioButtonUncheckedIcon from '@mui/icons-material/RadioButtonUnchecked';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import ViewSidebarIcon from '@mui/icons-material/ViewSidebar';
import HomeIcon from '@mui/icons-material/Home';
import ChurchIcon from '@mui/icons-material/Church';
import MusicNoteIcon from '@mui/icons-material/MusicNote';

// Re-exported names matching lucide-react usage in the project
export const Mail = (props: any) => <MailIcon {...props} />;
export const Phone = (props: any) => <PhoneIcon {...props} />;
export const MapPin = (props: any) => <PlaceIcon {...props} />;
export const Facebook = (props: any) => <FacebookIcon {...props} />;
export const Instagram = (props: any) => <InstagramIcon {...props} />;
export const Youtube = (props: any) => <YouTubeIcon {...props} />;
export const Heart = (props: any) => <FavoriteIcon {...props} />;
export const Users = (props: any) => <GroupIcon {...props} />;
export const BookOpen = (props: any) => <MenuBookIcon {...props} />;
export const Globe = (props: any) => <PublicIcon {...props} />;
export const Baby = (props: any) => <ChildFriendlyIcon {...props} />;
export const GraduationCap = (props: any) => <SchoolIcon {...props} />;
export const Handshake = (props: any) => <HandshakeIcon {...props} />;
export const Clock = (props: any) => <AccessTimeIcon {...props} />;
export const CalendarDays = (props: any) => <EventIcon {...props} />;
export const Calendar = (props: any) => <EventIcon {...props} />;
export const Menu = (props: any) => <MenuIcon {...props} />;
export const X = (props: any) => <CloseIcon {...props} />;
export const SearchIcon = (props: any) => <MuiSearchIcon {...props} />;
export const ChevronDownIcon = (props: any) => <ExpandMoreIcon {...props} />;
export const ChevronRight = (props: any) => <ChevronRightIcon {...props} />;
export const MoreHorizontal = (props: any) => <MoreHorizIcon {...props} />;
export const ChevronLeft = (props: any) => <ChevronLeftIcon {...props} />;
export const ArrowLeft = (props: any) => <ArrowBackIcon {...props} />;
export const ArrowRight = (props: any) => <ArrowForwardIcon {...props} />;
export const Check = (props: any) => <MuiCheckIcon {...props} />;
export const CheckIconExport = (props: any) => <MuiCheckIcon {...props} />;
export const CheckIcon = (props: any) => <MuiCheckIcon {...props} />;
export const XIcon = (props: any) => <CloseIcon {...props} />;
export const MinusIcon = (props: any) => <RemoveIcon {...props} />;
export const GripVerticalIcon = (props: any) => <DragIndicatorIcon {...props} />;
export const CircleIcon = (props: any) => <RadioButtonUncheckedIcon {...props} />;
export const ChevronUpIcon = (props: any) => <KeyboardArrowUpIcon {...props} />;
export const PanelLeftIcon = (props: any) => <ViewSidebarIcon {...props} />;
export const Home = (props: any) => <HomeIcon {...props} />;
export const Church = (props: any) => <ChurchIcon {...props} />;
export const Music = (props: any) => <MusicNoteIcon {...props} />;

// Default export is empty to keep commonjs consumers happy
export default {};
