export const organizationSections = [
  {
    title: "Parish Under Forane",
    items: [
      "St. Antony’s Church, Perambra",
      "St. Joseph’s Church, Aloor",
      "Our Lady of Grace Church, Aloor (West)",
      "Little Flower Church, Potta",
      "Our Lady of Rosary Church, Karoor",
      "Our Lady of Fathima Church, Vellanchira",
      "Our Lady of Grace Church, Thuruthiparambu",
      "Our Lady of Perpetual Help Church, West Chalakudy",
      "St. Sebastian’s Church, Thachudaparambu",
      "St. Joseph’s Church, North Chalakudy",
      "St. Antony’s Church, Kottatt",
      "Our Lady of Perpetual Help Church, Koodapuzha",
      "Our Lady of Lourdes Church, Elinjipra",
      "St. Francis Assisi Church, Bethlehem-Elinjipra",
      "St. Joseph’s Church, Mettipadam",
      "St. George Church, Pariyaram",
      "St. Mary’s, Thessery",
    ],
    accent: "#f59e0b",
  },
  {
    title: "Main Chapels (Kurishe Palli)",
    items: [
      "St. Mary's Chapel, Chenathunad",
      "Our Lady of Lourdes Chapel, Mariyapuram",
    ],
    accent: "#1d4ed8",
  },
  {
    title: "Chapels",
    items: [
      "Sacred Heart Chapel (Church Compound)",
      "St. Mary's Chapel (South Bazaar)",
      "St. Mary's Chapel (Chenathunad)",
      "St. Roch's Chapel (Govt. Hospital)",
      "St. Sebastian's Chapel (Vettukadavu)",
      "St. Sebastian's Chapel (Idukoodu)",
      "St. Sebastian's Chapel (Market Road)",
      "St. Joseph's Chapel (Koodapuzha)",
      "St. Sebastian's Chapel (Near ITI Puthuparambu)",
      "St. Antony's Chapel (Opposite KSRTC)",
      "Cross Chapel - West Bazaar",
      "Holy Cross - Railway Station",
    ],
    accent: "#7c3aed",
  },
  {
    title: "Schools Under Church",
    items: ["St.Mary's LP School Chalakudy"],
    accent: "#16a34a",
  },
];
